name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run tests with Playwright
      run: |
        pytest --maxfail=1 --disable-warnings --capture=no --html=report.html
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-report
        path: report.html
